services:
  vue:
    build: vue
    restart: always

  api:
    build: api
    restart: always
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - 3301:3300
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MySql123.
      MYSQL_DATABASE: app_db
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    build: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - vue
      - api

volumes:
  mysql-data: